version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fundshield_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '55432:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
